ui:
  app:
    url: ${UI_APP_URL}

keys:
  private: ${PRIVATE_KEY}
  public: ${PUBLIC_KEY}
spring:
  application:
    name: auth-server
  cloud:
    discovery:
      enabled: true
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    hikari:
      connection-test-query: select 1
  jpa:
    database: POSTGRESQL
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: ${POSTGRES_DATABASE}
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${EUREKA_USERNAME}:${EUREKA_PASSWORD}@${EUREKA_HOST}:${EUREKA_PORT}/eureka/
